[package]
name = "northstar-portal"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["cdylib", "lib"]

[features]
default = []
no-entrypoint = []
bpf-entrypoint = []
test-verifier = []
zk-verifier-prototype = ["dep:groth16-solana", "dep:northstar-zk-types"]

[dependencies]
base64-no-std = { package = "base64", version = "0.23.0", default-features = false }
pinocchio = "0.11.2"
pinocchio-system = "0.6.1"
pinocchio-log = "0.5.1"
borsh = { version = "1", default-features = false, features = ["derive"] }
groth16-solana = { git = "https://github.com/Lightprotocol/groth16-solana", rev = "43fee1a67e91c0df7bb4edad5ba87ae4602aa208", optional = true }
northstar-zk-types = { workspace = true, optional = true }
solana-sha256-hasher = { workspace = true, features = ["sha2"] }
pinocchio-idl-macros = "=0.1.1"
solana-address = { version = "=2.6.1", default-features = false, features = ["borsh"] }

[target.'cfg(not(target_os = "solana"))'.dependencies]
solana-pubkey = { workspace = true, features = ["curve25519"] }

[dev-dependencies]
bincode = { workspace = true }
hex = "0.4"
serde_json = "1"
solana-program-test = { workspace = true }
solana-sdk-ids = { workspace = true }
tokio = { workspace = true, features = ["full"] }
solana-pubkey = { workspace = true }
solana-signature = { workspace = true }
solana-signer = { workspace = true }
solana-instruction = { workspace = true }
solana-transaction = { workspace = true }
solana-keypair = { workspace = true }
solana-account = { workspace = true }
solana-compute-budget-interface = { workspace = true }
solana-system-interface = { workspace = true }
solana-hash = { workspace = true }
solana-commitment-config = { workspace = true }
solana-rpc-client = { workspace = true }

[lints.rust]
unexpected_cfgs = "allow"
