#!/usr/bin/env bash

here=$(dirname "$0")

cargo --list | grep -q "^\s*build-sbf"
found=$?
if [[ $found -ne 0 ]]; then
  cargo install cargo-build-sbf
fi
# Sonic: Keep Northstar's validated SBF ABI/compiler independent of CLI release defaults.
exec cargo build-sbf --arch v0 --tools-version v1.56 "$@"
