use pinocchio::program_error::ProgramError;

#[repr(u32)]
pub enum PortalError {
    InvalidInstruction = 0,
    InvalidAccountData = 1,
    SessionExpired = 2,
    SessionStillActive = 3,
    Unauthorized = 4,
    InsufficientFees = 5,
    ArithmeticOverflow = 6,
    InvalidPdaSeeds = 7,
    SessionAccountOwnerMismatch = 8,
    SessionDeserializeFailed = 9,
    SessionStateInvalid = 10,
    DepositReceiptDeserializeFailed = 11,
    DepositReceiptStateInvalid = 12,
    DelegatedAccountOwnerMismatch = 13,
    DelegationRecordAlreadyInitialized = 14,
    DelegationRecordDeserializeFailed = 15,
    DelegationRecordStateInvalid = 16,
    DelegateBufferOwnerMismatch = 17,
    DelegateBufferSizeMismatch = 18,
    SettlementInProgress = 19,
    SettlementNotInProgress = 20,
    SettlementTooEarly = 21,
    SettlementErSlotNotAdvanced = 22,
    SettlementErSlotMismatch = 23,
    SettlementChecksumMismatch = 24,
    SettlementChunkTooLarge = 25,
    SettlementChunkOutOfBounds = 26,
    SettlementUnauthorizedAbort = 27,
    DelegationRecordAccountMismatch = 28,
    DelegatedAccountDataNotEmpty = 29,
    SettlementLamportsNotConserved = 30,
    SettlementLamportsBelowRentExempt = 31,
    WithdrawalSinkMismatch = 32,
    CheckpointCommitTooEarly = 33,
    CheckpointStateInvalid = 34,
    CheckpointUnauthorizedCancel = 35,
    CheckpointErSlotNotAdvanced = 36,
    CheckpointDeserializeFailed = 37,
    CheckpointCursorStateInvalid = 38,
    CheckpointCursorDeserializeFailed = 39,
    CheckpointBondInsufficient = 40,
    CheckpointBondAlreadyResolved = 41,
    CheckpointChallenged = 42,
    CheckpointChallengeWindowClosed = 43,
    StepProofStateInvalid = 44,
    StepProofDeserializeFailed = 45,
    StepProofAlreadySealed = 46,
    StepProofNotSealed = 47,
    StepProofChunkOutOfBounds = 48,
    StepProofCheckpointMismatch = 49,
    StepProofVerifierUnavailable = 50,
    StepProofHashMismatch = 51,
    CheckpointCancelWindowClosed = 52,
    CheckpointPreviousRootMismatch = 53,
    CheckpointActiveExists = 54,
    StepProofPublicInputMismatch = 55,
    ChallengeStateInvalid = 56,
    ChallengeDeserializeFailed = 57,
    ChallengeTurnInvalid = 58,
    ChallengeDeadlineNotReached = 59,
    ChallengeResponseInvalid = 60,
    DataAvailabilityStateInvalid = 61,
    DataAvailabilityDeserializeFailed = 62,
    DataAvailabilityCommitmentMismatch = 63,
    CheckpointChallengeWindowTooLong = 64,
    StepProofVerificationFailed = 65,
}

impl From<PortalError> for ProgramError {
    fn from(e: PortalError) -> Self {
        ProgramError::Custom(e as u32)
    }
}
