[package]
name = "northstar-zk-prover"
version = "0.1.0"
edition = "2021"

[dependencies]
ark-bn254 = "0.6"
ark-ff = "0.6"
ark-groth16 = "0.6"
ark-relations = "0.6"
ark-r1cs-std = "0.6"
ark-serialize = "0.6"
ark-std = "0.6"
hex = "0.4"
northstar-zk-types = { workspace = true }
northstar-transaction-proof = { workspace = true }
solana-sbpf = { workspace = true }
rand_chacha = "0.10"
serde_json = "1"
sha2 = "0.11"
northstar-replay-harness = { workspace = true }


[lints]
workspace = true
